services:
  # Production service - runs examples and generates plots
  plotlib:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plotlib-production
    volumes:
      - ./output:/app/output
    environment:
      - PLOTLIB_OUTPUT_DIR=/app/output
    command: >
      /bin/sh -c "
      echo 'PlotLib Production Container - Running All Examples...' &&
      cd /app &&
      echo 'Running beginner examples...' &&
      for example in /app/build/examples/[0-9][0-9]_*; do
        if [ -x \"$$example\" ]; then
          echo \"  Running $$(basename $$example)...\"
          $$example
        fi
      done &&
      echo 'Running advanced examples...' &&
      for example in /app/build/examples/advanced_*; do
        if [ -x \"$$example\" ]; then
          echo \"  Running $$(basename $$example)...\"
          $$example
        fi
      done &&
      echo 'Running tests...' &&
      /app/build/tests/basic_tests &&
      echo 'All examples and tests completed! Check ./output for generated plots.'
      "

  # Development service - interactive shell for development
  plotlib-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plotlib-development
    volumes:
      - .:/app
      - ./output:/app/output
    working_dir: /app
    environment:
      - PLOTLIB_OUTPUT_DIR=/app/output
    command: /bin/sh
    stdin_open: true
    tty: true

  # Demo service - runs specific examples for demonstrations
  plotlib-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plotlib-demo
    volumes:
      - ./output:/app/output
    environment:
      - PLOTLIB_OUTPUT_DIR=/app/output
      - DEMO_TYPE=${DEMO_TYPE:-beginner}
    command: >
      /bin/sh -c "
      echo 'PlotLib Demo Container - Running $${DEMO_TYPE} Examples...' &&
      cd /app &&
      if [ \"$$DEMO_TYPE\" = \"beginner\" ]; then
        for example in /app/build/examples/[0-9][0-9]_*; do
          if [ -x \"$$example\" ]; then
            echo \"  Running $$(basename $$example)...\"
            $$example
          fi
        done
      elif [ \"$$DEMO_TYPE\" = \"advanced\" ]; then
        for example in /app/build/examples/advanced_*; do
          if [ -x \"$$example\" ]; then
            echo \"  Running $$(basename $$example)...\"
            $$example
          fi
        done
      else
        echo \"Running single example: $$DEMO_TYPE\"
        if [ -x \"/app/build/examples/$$DEMO_TYPE\" ]; then
          /app/build/examples/$$DEMO_TYPE
        else
          echo \"Error: Example $$DEMO_TYPE not found or not executable\"
          exit 1
        fi
      fi &&
      echo 'Demo completed! Check ./output for generated plots.'
      "

  # Test service - runs only tests
  plotlib-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plotlib-test
    command: >
      /bin/sh -c "
      echo 'PlotLib Test Container - Running Tests...' &&
      /app/build/tests/basic_tests &&
      echo 'Tests completed successfully!'
      " 