services:
  # Main service - runs all examples and generates plots
  plotlib:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plotlib
    volumes:
      - ./output:/app/output
    environment:
      - PLOTLIB_OUTPUT_DIR=/app/output
    command: >
      /bin/sh -c "
      echo 'PlotLib Container - Running All Examples...' &&
      cd /app &&
      echo 'Running beginner examples...' &&
      for example in /app/build/examples/[0-9][0-9]_*; do
        if [ -x \"$$example\" ]; then
          echo \"  Running $$(basename $$example)...\"
          $$example
        fi
      done &&
      echo 'Running advanced examples...' &&
      for example in /app/build/examples/advanced_*; do
        if [ -x \"$$example\" ]; then
          echo \"  Running $$(basename $$example)...\"
          $$example
        fi
      done &&
      echo 'Running plot_types examples...' &&
      for example in /app/build/examples/plot_types_*; do
        if [ -x \"$$example\" ]; then
          echo \"  Running $$(basename $$example)...\"
          $$example
        fi
      done &&
      echo 'Running tests...' &&
      /app/build/tests/basic_tests &&
      echo 'All examples and tests completed! Check ./output for generated plots.'
      "